spring:
  datasource:
    url: ${ERP_DB_URL}
    username: ${ERP_DB_USERNAME}
    password: ${ERP_DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ERP_ISSUER_URI}